[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["cd order-pay-backend && npm install"]

[phases.build]
cmds = ["cd order-pay-backend && npm run build"]

[start]
cmd = "cd order-pay-backend && npm run start:prod" 