services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: orderpaydb
    ports:
      - "3307:3306"


  api:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: orderpaydb
      DB_SYNC: "true"

  dev:
    build:
      context: .
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null
    depends_on:
      - db
